# The configuration for the Bedrock Mechanics Mod.

[gui]
is_enabled = true # Whether the GUI is enabled.
is_paper_doll_enabled = true
show_position = true
show_fps = false
paper_doll_rotation = 20
paper_doll_scale = 20
position_y = 5
position_x = 5
screen_safe_area = 0

[mechanics]
allow_fast_block_placement = true
key_binding_look_speed = 50.0

[controller]
is_enabled = false
selected_controller = 0
dead_zone = 0.25
